services:
  service_a:
    build: ../service_a
    image: service_a:latest
    network_mode: host
    ports:
      - "8000:8000"

  service_b:
    build: ../service_b
    image: service_b:latest
    network_mode: host
    ports:
      - "8001:8001"
    depends_on:
      - service_a